
def additoin(x, y):
    x = 10
    y = 20
    print("Addition:", x + b)



try:
     additoin(10, 20)
except NameError:
    print("the error is in Nameerror try again")
except:
    print("thar is in error")
else:
    print("the operation is successful")